trigger:
  batch: true
  branches:
    include:
      - "master"

variables:
  - name: buildConfiguration
    value: 'release'
  - name: DACPACSolutionBaseName
    value: SFA.DAS.Reservations.Database
  - group: RELEASE Management Resources
  - group: RELEASE das-reservations-api
  - name: SolutionBaseName
    value: SFA.DAS.Reservations
  - name: Deploy
    value: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.Reason'], 'PullRequest'))]

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/2.1.18
    endpoint: SkillsFundingAgency
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/5.1.8
    endpoint: SkillsFundingAgency
  pipelines:
  - pipeline: das-employer-config
    project: Digital Apprenticeship Service
    source: das-employer-config
    branch: master

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
  - template: azure-pipelines-templates/build/job/dacpac-template.yml@das-platform-building-blocks
    parameters:
      SolutionBaseName: $(DACPACSolutionBaseName)
      SqlProjectPath: src/$(DACPACSolutionBaseName)/$(DACPACSolutionBaseName).sqlproj
  - template: azure-pipelines-templates/build/job/dacpac-template.yml@das-platform-building-blocks
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      SqlProjectPath: src/$(SolutionBaseName).Database/$(SolutionBaseName).Database.sqlproj

- stage: Deploy_AT
  dependsOn: Build
  displayName: Deploy to AT
  condition: and(succeeded(), eq(variables.Deploy, 'true'))
  variables:
  - group: DevTest Management Resources
  - group: AT DevTest Shared Resources
  - group: AT das-reservations-api
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: AT
      SolutionBaseName: $(SolutionBaseName)
      ServiceConnection: SFA-DAS-DevTest-ARM
      OverrideBlockOnPossibleDataLoss: ${{ parameters.OverrideBlockOnPossibleDataLoss  }}
