trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

variables:
  buildConfiguration: 'release'
  buildPlatform: 'anycpu'

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.10
    endpoint: SkillsFundingAgency

jobs:
- job: 'CodeBuild'
  pool:
    name: DAS - Continuous Integration Agents
    demands: LATEST_DOTNET_VERSION -equals 3.1
  workspace:
    clean: all
  steps:
  - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

  - template: azure-pipelines-templates/build/step/app-build.yml@das-platform-building-blocks

  - template: azure-pipelines-templates/build/step/dependency-check.yml@das-platform-building-blocks

  - task: DotNetCoreCLI@2
    displayName: 'Publish Website'
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'src/SFA.DAS.Reservations.Api/SFA.DAS.Reservations.Api.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet pack'
    inputs:
      command: pack
      packagesToPack: src/SFA.DAS.Reservations.Messages/SFA.DAS.Reservations.Messages.csproj
      packDirectory: '$(build.artifactstagingdirectory)/publish'
      versioningScheme: byBuildNumber
      buildProperties: 'Version="$(Build.BuildNumber)"'

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      contents: |
        azure/**
      targetFolder: '$(build.artifactstagingdirectory)/publish'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      pathtoPublish: '$(build.artifactstagingdirectory)/publish'

- job: 'DACPACBuild'
  pool: 
    vmImage: 'windows-2019'
  workspace:
    clean: all
  steps:
  - task: VSBuild@1
    displayName: 'Build DACPAC'
    inputs:
      solution: 'src/SFA.DAS.Reservations.Database/SFA.DAS.Reservations.Database.sqlproj'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      msbuildArgs: '/p:PackageLocation="$(build.artifactstagingdirectory)/publish"'
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      contents: |
        src/**/*.dacpac
      targetFolder: '$(build.artifactstagingdirectory)/publish'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      pathtoPublish: '$(build.artifactstagingdirectory)/publish'
