jobs:
- job: DACPACBuild
  pool:
    name: DAS - Continuous Integration
    demands: Agent.OS -equals Windows_NT
  workspace:
    clean: all
  steps:
  - task: VSBuild@1
    displayName: Build DACPAC
    inputs:
      solution: src/SFA.DAS.Reservations.Database/SFA.DAS.Reservations.Database.sqlproj
      platform: any cpu
      configuration: $(buildConfiguration)
      msbuildArgs: /p:PackageLocation="$(build.artifactstagingdirectory)/publish"
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      contents: |
        src/**/*.dacpac
      targetFolder: $(build.artifactstagingdirectory)/publish
  - task: PublishPipelineArtifact@1
    displayName: Publish Artifact - ReservationsApi
    inputs:
      targetPath: $(build.artifactstagingdirectory)/publish
      artifactName: ReservationsApiDacpacArtifact